# Generated by Django 3.2.9 on 2022-03-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildsetting',
            name='value',
            field=models.TextField(),
        ),
    ]
