# Generated by Django 3.2.9 on 2022-03-18 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0003_raidgroup_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='character_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guild.gameclass'),
        ),
    ]
