# Generated by Django 3.2.9 on 2022-03-18 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0004_auto_20220318_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='raidgroup',
            name='schedule',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
