# Generated by Django 3.2.9 on 2022-03-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0005_auto_20220318_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='discord_username',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
