# Generated by Django 3.2.9 on 2022-03-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0006_member_discord_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidgroup',
            name='raid_size',
            field=models.IntegerField(default=0),
        ),
    ]
