# Generated by Django 3.2.9 on 2022-03-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0008_character_public_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='public_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
