# Generated by Django 3.2.9 on 2022-03-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0009_alter_character_public_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='ilevel',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
