# Generated by Django 4.0.3 on 2022-04-05 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0012_auto_20220328_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='raid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guild.raidgroup'),
        ),
    ]
